<?php
return array(
	'sliders'     => __( 'Slider Widgets',  'hootkit' ),
	'content'     => __( 'Content Widgets', 'hootkit' ),
	'post'        => __( 'Post Widgets',    'hootkit' ),
	'display'     => __( 'Display Widgets', 'hootkit' ),
	'woocom'      => __( 'Woocommerce',     'hootkit' ),
	'misc'        => __( 'Misc. Features',  'hootkit' ),

	'image'            => __( 'HK > Slider Images',       'hootkit' ),
	'slider-image'     => __( 'HK > Slider Images',       'hootkit' ),
	'postimage'        => __( 'HK > Posts Slider',        'hootkit' ),
	'slider-postimage' => __( 'HK > Posts Slider',        'hootkit' ),

	'carousel'         => __( 'HK > Carousel',            'hootkit' ),
	'postcarousel'     => __( 'HK > Posts Carousel',      'hootkit' ),
	'postlistcarousel' => __( 'HK > Posts List Carousel', 'hootkit' ),

	'productcarousel'         => __( 'HK > Products Carousel',      'hootkit' ),
	'productlistcarousel'     => __( 'HK > Products List Carousel', 'hootkit' ),

	'content-products-blocks' => __( 'HK > Products Blocks',       'hootkit' ),
	'product-list'            => __( 'HK > Products List',         'hootkit' ),
	'products-ticker'         => __( 'HK > Products Ticker',       'hootkit' ),
	'products-search'         => __( 'HK > Products Search',       'hootkit' ),
	'products-carticon'       => __( 'HK > Products Cart Icon',    'hootkit' ),
	'fly-cart'                => __( 'Offscreen WooCommerce Cart', 'hootkit' ),

	'announce'             => __( 'HK > Announce',       'hootkit' ),
	'content-blocks'       => __( 'HK > Content Blocks', 'hootkit' ),
	'content-posts-blocks' => __( 'HK > Posts Blocks',   'hootkit' ),
	'cta'                  => __( 'HK > Call To Action', 'hootkit' ),
	'icon'                 => __( 'HK > Icon',           'hootkit' ),
	'post-grid'            => __( 'HK > Posts Grid',     'hootkit' ),
	'post-list'            => __( 'HK > Posts List',     'hootkit' ),
	'social-icons'         => __( 'HK > Social Icons',   'hootkit' ),
	'ticker'               => __( 'HK > Ticker',         'hootkit' ),
	'ticker-posts'         => __( 'HK > Posts Ticker',   'hootkit' ),
	'profile'              => __( 'HK > About/Profile',  'hootkit' ),
	'content-grid'         => __( 'HK > Content Grid',   'hootkit' ),
	'cover-image'          => __( 'HK > Cover Image',    'hootkit' ),

	'contact-info'         => __( 'HK > Contact Info',   'hootkit' ),
	'number-blocks'        => __( 'HK > Number Blocks',  'hootkit' ),
	'vcards'               => __( 'HK > Vcards',         'hootkit' ),
	'buttons'              => __( 'HK > Buttons',        'hootkit' ),
	'icon-list'            => __( 'HK > Icon List',      'hootkit' ),
	'notice'               => __( 'HK > Notice Box',     'hootkit' ),
	'toggle'               => __( 'HK > Toggle',         'hootkit' ),
	'tabs'                 => __( 'HK > Tabs',           'hootkit' ),

	'top-banner'      => __( 'Top Banner',        'hootkit' ),
	'shortcode-timer' => __( 'Timer (shortcode)', 'hootkit' ),

	'white'        => __( 'White',           'hootkit' ),
	'black'        => __( 'Black',           'hootkit' ),
	'brown'        => __( 'Brown',           'hootkit' ),
	'brownbright'  => __( 'Brown (Bright)',  'hootkit' ),
	'blue'         => __( 'Blue',            'hootkit' ),
	'bluebright'   => __( 'Blue (Bright)',   'hootkit' ),
	'cyan'         => __( 'Cyan',            'hootkit' ),
	'cyanbright'   => __( 'Cyan (Bright)',   'hootkit' ),
	'green'        => __( 'Green',           'hootkit' ),
	'greenbright'  => __( 'Green (Bright)',  'hootkit' ),
	'yellow'       => __( 'Yellow',          'hootkit' ),
	'yellowbright' => __( 'Yellow (Bright)', 'hootkit' ),
	'amber'        => __( 'Amber',           'hootkit' ),
	'amberbright'  => __( 'Amber (Bright)',  'hootkit' ),
	'orange'       => __( 'Orange',          'hootkit' ),
	'orangebright' => __( 'Orange (Bright)', 'hootkit' ),
	'red'          => __( 'Red',             'hootkit' ),
	'redbright'    => __( 'Red (Bright)',    'hootkit' ),
	'pink'         => __( 'Pink',            'hootkit' ),
	'pinkbright'   => __( 'Pink (Bright)',   'hootkit' ),

);